ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE DATOS
    DATAFILE 'datos01.dbf'
    SIZE 100M
    AUTOEXTEND ON
    NEXT 10M;

CREATE USER POLI001 IDENTIFIED BY Poli001Pass123
    DEFAULT TABLESPACE DATOS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON DATOS;

GRANT CREATE SESSION TO POLI001;
GRANT CONNECT TO POLI001;
GRANT RESOURCE TO POLI001;

COMMIT;
